language: node_js
node_js: v8
sudo: false
addons:
  firefox: latest

env:
  global:
  - secure: M1LN50Mt/UWrrng0yDY2BeWGrbe0HA4wfSoojyJ/MT0AAHmKYQVsuDnG8CqcRmK5g/xDja8+LH2QQcGbkHWFboRrAql8/iooVzqxhAICyiO6ju2F+bnymjMfgT2+hV8yUda9qGvV8PiaqUA5Rvcy8S6GXO/8JDGJRQN3t+1VIFg=
  - secure: FMf+FEwbGx3Rr0jUW7LypFnMn4fuicAaBMvylw/h3VACIc1gHg0aZrQ13VPpEB4XfW8igqRjbUxwDqKhKr7vOMqezYWenUbq+Xcs2Zr6ZxV7t9mYqqFqHOhW+1WUN8HvnBMu7shVaeQwqm95YhX1HLsSngKCc5Cgs8V60+Nh0Hg=

after_success:
- mkdir -p dist
- npm run package

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: dist/*.zip
  api_key:
    secure: R4J0DcS66NSadM6q/Ufr4JgFnAaOUDLEBTqMV5h7w+sNNEsLDLauOQ61aEd6W0oL4aH4D0gvwz0OxXH0sBj1y4UYBdP/DpiJJ2ATYjmohtH6nN15baJZU41LQnICSRzo4I94B1wIog1V33YGtiTa/hN0f3NjVIz+8oz+brHPjag=
  on:
    tags: true
