language: node_js
node_js: v10
cache: npm

after_success:
- mkdir -p dist
- npm run package

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: dist/*.zip
  api_key:
    secure: R4J0DcS66NSadM6q/Ufr4JgFnAaOUDLEBTqMV5h7w+sNNEsLDLauOQ61aEd6W0oL4aH4D0gvwz0OxXH0sBj1y4UYBdP/DpiJJ2ATYjmohtH6nN15baJZU41LQnICSRzo4I94B1wIog1V33YGtiTa/hN0f3NjVIz+8oz+brHPjag=
  on:
    tags: true
